# ERROR OBJECT

#   DOCTOR
EO_DOCTOR_FIRST_NAME = "DOCTOR_FIRST_NAME"
EO_DOCTOR_LAST_NAME = "DOCTOR_LAST_NAME"
EO_DOCTOR_EMAIL = "DOCTOR_EMAIL"
EO_DOCTOR_PASSWORD = "DOCTOR_PASSWORD"
EO_DOCTOR_REPEAT_PASSWORD = "DOCTOR_REPEAT_PASSWORD"

EO_PATIENT_FIRST_NAME = "PATIENT_FIRST_NAME"
EO_PATIENT_LAST_NAME = "PATIENT_LAST_NAME"

EO_VARIABLE_INPUT_NAME = "VARIABLE_INPUT_NAME"
EO_VARIABLE_INPUT_VALUES = "VARIABLE_INPUT_VALUES"
EO_VARIABLE_INPUT_SCALE = "VARIABLE_INPUT_SCALE"

EO_SKL_IMG_NAME = "SKL_IMG_NAME"

# ERROR TYPE
ET_EMPTY = "EMPTY"
ET_INCORRECT = "INCORRECT"
ET_NOT_VALID = "NOT_VALID"
ET_NOT_MATCH = "NOT_MATCH"
ET_EXISTS = "EXISTS"
ET_NOT_SELECTED = "NOT_SELECTED"
