CREATE_ACCOUNT_VIEW = "CREATE_ACCOUNT_VIEW"
LOGIN_VIEW = "LOGIN_VIEW"
PATIENTS_VIEW = "PATIENTS_VIEW"
ADD_PATIENT_VIEW = "ADD_PATIENT_VIEW"

DB_PATH = "db"
DB_NAME = "skin_application.sqlite"
DB_PATH_NAME = DB_PATH + "/" + DB_NAME

DB_SCRIPT_PATH = "db/scripts"
DB_SCRIPT_NAME = "tables_creation.sql"
DB_SCRIPT_PATH_NAME = DB_SCRIPT_PATH + "/" + DB_SCRIPT_NAME

TABLE_DOCTORS = "DOCTORS"
TABLE_PATIENTS = "PATIENTS"
COLUMN_DOCTORS_FIRST_NAME = "first_name"
COLUMN_DOCTORS_LAST_NAME = "last_name"
COLUMN_DOCTORS_PASSWORD = "password"
