import os

PROJECT_FOLDER = os.sep.join(__file__.split(os.sep)[:-2])
_S = os.sep

CREATE_ACCOUNT_VIEW = "CREATE_ACCOUNT_VIEW"
LOGIN_VIEW = "LOGIN_VIEW"
PATIENTS_VIEW = "PATIENTS_VIEW"
ADD_PATIENT_VIEW = "ADD_PATIENT_VIEW"
ADD_PATIENT_MI_VIEW = "ADD_PATIENT_MI_VIEW"
ADD_PATIENT_PREVIEW_VIEW = "ADD_PATIENT_PREVIEW_VIEW"

DB_PATH = PROJECT_FOLDER + _S + "db"
DB_NAME = "skin_application.sqlite"
DB_PATH_NAME = DB_PATH + _S + DB_NAME

DB_SCRIPT_PATH = DB_PATH + _S + "scripts"
DB_SCRIPT_NAME = "tables_creation.sql"
DB_SCRIPT_PATH_NAME = DB_SCRIPT_PATH + _S + DB_SCRIPT_NAME

FILES_PATH = PROJECT_FOLDER + "/assets/files"
FILES_MEDICAL_INFORMATION_PATH = FILES_PATH + "/medical_information"

STYLES_PATH = PROJECT_FOLDER + "/src/views/ui/styles"
GLOBAL_STYLES_NAME = "global.css"
GLOBAL_STYLES_PATH_NAME = STYLES_PATH + _S + GLOBAL_STYLES_NAME


TABLE_DOCTORS = "DOCTORS"
TABLE_PATIENTS = "PATIENTS"
COLUMN_DOCTORS_FIRST_NAME = "first_name"
COLUMN_DOCTORS_LAST_NAME = "last_name"
COLUMN_DOCTORS_PASSWORD = "password"
